name: landman_website
description: A responsive Flutter app implementing the Account Settings design
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.5.6
  intl: ^0.19.0
  archive: ^3.6.1
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # Lottie animations
  # Add Lottie asset JSON files under assets/images/

